### ISSUE TITLE
Strange error saving interpolate on windows

### ISSUE THREAD

**Issue by mtugsbayar** [shayqn/video-labeler#4]
Having a problem saving labels that include interpolate. This error does not show up if I don't use interpolate. utils file is same as master. INTERP was used in this manner ["still", "INTERP", 0, 0, 0, 0, "still"] 

**Error log:** 

UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-9-6fb71aae3a4c> in <module>
----> 1 vl.batchFrameLabel(video_file=movie_file,labels_file=labels_file,batch_size=250,label_dict=label_dict)

~\video-labeler\videolabeler\utils.py in batchFrameLabel(video_file, labels_file, batch_size, label_dict)
    361             if save_labels is True:
    362                 master_labels = master_labels.append(label_df)
--> 363                 master_labels.to_csv(labels_file)
    364 
    365                 #print progress

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\pandas\core\generic.py in to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, line_terminator, chunksize, date_format, doublequote, escapechar, decimal)
   3226             decimal=decimal,
   3227         )
-> 3228         formatter.save()
   3229 
   3230         if path_or_buf is None:

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\pandas\io\formats\csvs.py in save(self)
    200                 self.writer = UnicodeWriter(f, **writer_kwargs)
    201 
--> 202             self._save()
    203 
    204         finally:

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\pandas\io\formats\csvs.py in _save(self)
    322                 break
    323 
--> 324             self._save_chunk(start_i, end_i)
    325 
    326     def _save_chunk(self, start_i, end_i):

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\pandas\io\formats\csvs.py in _save_chunk(self, start_i, end_i)
    354         )
    355 
--> 356         libwriters.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)

pandas/_libs/writers.pyx in pandas._libs.writers.write_csv_rows()

UnicodeEncodeError: 'utf-8' codec can't encode character '\udc73' in position 3: surrogates not allowed

**Comment by shayqn** [comment]
I would try the following: 
Try annotating a single batch of frames by: 
```
frames = vl.LoadVideoFrames(video_file,num_frames=100)
labels = vl.PlayAndLabelFrames(frames,label_dict = {'i':'INTERP','w':'walking','t':'turning','s':'standing'},
                        return_labeled_frames=False)
interpolated_labels = vl.interpolate_labels(labels)
```
and see if something in interpolated_labels looks funny / unexpected.

**Comment by mtugsbayar** [comment]
I get another unicode encode error when I try to print interpolated_labels. I tried to view it with a variable viewer in jupyter, but I can't see the array there either. I can see array just fine if I use the other labels. I'm wondering if this is a Windows-related encoding thing. I could potentially just run it on Linux.

**Error log**

UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-8-0c55d6809e19> in <module>
----> 1 print(interpolated_labels)

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in _array_str_implementation(a, max_line_width, precision, suppress_small, array2string)
   1527         return _guarded_str(np.ndarray.__getitem__(a, ()))
   1528 
-> 1529     return array2string(a, max_line_width, precision, suppress_small, ' ', "")
   1530 
   1531 

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in array2string(a, max_line_width, precision, suppress_small, separator, prefix, style, formatter, threshold, edgeitems, sign, floatmode, suffix, **kwarg)
    698         return "[]"
    699 
--> 700     return _array2string(a, options, separator, prefix)
    701 
    702 

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in wrapper(self, *args, **kwargs)
    470             repr_running.add(key)
    471             try:
--> 472                 return f(self, *args, **kwargs)
    473             finally:
    474                 repr_running.discard(key)

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in _array2string(a, options, separator, prefix)
    505     lst = _formatArray(a, format_function, options['linewidth'],
    506                        next_line_prefix, separator, options['edgeitems'],
--> 507                        summary_insert, options['legacy'])
    508     return lst
    509 

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in _formatArray(a, format_function, line_width, next_line_prefix, separator, edge_items, summary_insert, legacy)
    826         return recurser(index=(),
    827                         hanging_indent=next_line_prefix,
--> 828                         curr_width=line_width)
    829     finally:
    830         # recursive closures have a cyclic reference to themselves, which

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in recurser(index, hanging_indent, curr_width)
    780 
    781             for i in range(trailing_items, 1, -1):
--> 782                 word = recurser(index + (-i,), next_hanging_indent, next_width)
    783                 s, line = _extendLine(
    784                     s, line, word, elem_width, hanging_indent, legacy)

~\AppData\Local\Continuum\anaconda3\envs\vid-label\lib\site-packages\numpy\core\arrayprint.py in recurser(index, hanging_indent, curr_width)
    734 
    735         if axes_left == 0:
--> 736             return format_function(a[index])
    737 
    738         # when recursing, add a space to align with the [ added, and reduce the

UnicodeDecodeError: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)

**Comment by mtugsbayar** [comment]
interpolate_labels function was not reading label as string type. Should be fixed now.
